on:
  workflow_dispatch:
    inputs:
      client_name:
        description: 'Client name (e.g., clientA)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests jinja2

    - name: Set environment variables
      run: |
        echo "CLIENT_NAME=${{ github.event.inputs.client_name }}" >> $GITHUB_ENV
        echo "TENANT_ID=${{ secrets[format('{0}_TENANT_ID', github.event.inputs.client_name)] }}" >> $GITHUB_ENV
        echo "CLIENT_ID=${{ secrets[format('{0}_CLIENT_ID', github.event.inputs.client_name)] }}" >> $GITHUB_ENV
        echo "CLIENT_SECRET=${{ secrets[format('{0}_CLIENT_SECRET', github.event.inputs.client_name)] }}" >> $GITHUB_ENV
        echo "CAPACITY_ID=${{ secrets[format('{0}_CAPACITY_ID', github.event.inputs.client_name)] }}" >> $GITHUB_ENV
        echo "WORKSPACES_JSON=${{ secrets[format('{0}_WORKSPACES_JSON', github.event.inputs.client_name)] }}" >> $GITHUB_ENV

    - name: Render config from template
      run: python scripts/render_config.py

    - name: Run deployment script
      run: python scripts/deploy.py